### ISSUE TITLE
Bug: mux-player-react breaks in NextJS

### ISSUE THREAD

**Issue by iisalazar** [muxinc/elements#716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-player

### Which browsers are you using?

Chrome, Edge ("Edgeium")

### Which operating systems are you using?

Other (add details below)

### Description

Hey! I'm working on a project right now and we're using mux-player-react with NextJS. When I used the minimal styling of the component by importing from mux-player, it was throwing an error like this

```
SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
```

I already saw a [PR](https://github.com/muxinc/elements/pull/30) that fixes this (but for a separate package), and I want to add that to the mux-player package. 

### Steps to reproduce

1. Setup any nextjs app version 12.3.0
2. Install mux-player-react, import it, use it, add in the custom minimal style by importing from `@mux/mux-player/themes/minimal`
3. Run the nextjs app

### Current Behavior

NextJS app is throwing an error
![image](https://github.com/muxinc/elements/assets/19862244/700bb149-af8a-4a86-b93b-e73f2a39d7ae)

### Expected Behavior

App should run smoothly, the nextjs app should render the mux-player-react component with minimal style 

### Errors

![image](https://github.com/muxinc/elements/assets/19862244/77a6b117-1929-40f3-a56e-78745aeb061e)

### What version of the package are you using?

v1.11.3

**Comment by iisalazar** [comment]
To add, I was able to fix this locally by modifying the `package.json` file in `mux-player` in my `node_modules` directory. I just added the key-value pair `type: module` just like in the previous PR I referenced

![image](https://github.com/muxinc/elements/assets/19862244/ab587c40-da11-4881-b637-cf7fb1347876)
