### ISSUE TITLE
Issue: ReferenceError: module is not defined in ES module scope

### ISSUE THREAD

**Issue by Mithrandiirr** [muxinc/elements#739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Mux Elements/Packages does this apply to? Select all that apply

mux-video-react

### Which browsers are you using?

Chrome

### Which operating systems are you using?

None

### Description

I get this issue when build:
```Building client code ...
9:14:11 PM [vite] Error when evaluating SSR module /src/components/media/SanityMuxVideo.client.tsx?no-proxy:
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/runner/work/penny-morrison/penny-morrison/node_modules/@mux/mux-video-react/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/runner/work/penny-morrison/penny-morrison/node_modules/@mux/mux-video-react/dist/index.cjs.js:1:601
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at async nodeImport (/home/runner/work/penny-morrison/penny-morrison/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:50387:21)
    at async eval (/src/components/media/SanityMuxVideo.client.tsx?no-proxy:6:31)
    at async instantiateModule (/home/runner/work/penny-morrison/penny-morrison/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:50317:9)```
Please note this commit was working 7 hours ago, I reverted to that commit again but I still have this issue.

### Reduced test case

_No response_

### Steps to reproduce

1.Build Hydrogen 1 in Oxygen
2.Error: Deployment to Oxygen failed. Check the 'Build and Publish to Oxygen' step for more information.


### Current Behavior

Getting this issue while building a hydrogen1 project using oxygen.
I reverted to my latest working commit and got the issue whatsoever.

### Expected Behavior

Ideally building should result
```
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Building client code ...
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Building worker code ...

Done in 52.94s.
✅ Done in 53.09s.

🔍 Locating assets to upload... 
✅ Done in 0.01s.

🔑 Requesting asset upload... 
✅ Done in 1.09s.

☁️ Uploading assets... 
✅ Done in 1.77s.

🚀 Uploading deployment... 
✅ Done in 8.53s.

🙌 Successfully deployed!
```

### Errors

```
Building client code ...
9:14:11 PM [vite] Error when evaluating SSR module /src/components/media/SanityMuxVideo.client.tsx?no-proxy:
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/runner/work/penny-morrison/penny-morrison/node_modules/@mux/mux-video-react/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/runner/work/penny-morrison/penny-morrison/node_modules/@mux/mux-video-react/dist/index.cjs.js:1:601
    at ModuleJob.run (node:internal/modules/esm/module_job:[193](https://github.com/BMAS-Agency/penny-morrison/actions/runs/5860727676/job/15889389446#step:7:196):25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at async nodeImport (/home/runner/work/penny-morrison/penny-morrison/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:50387:21)
    at async eval (/src/components/media/SanityMuxVideo.client.tsx?no-proxy:6:31)
    at async instantiateModule (/home/runner/work/penny-morrison/penny-morrison/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:50317:9)
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Building client code ...
9:14:11 PM [vite] Error when evaluating SSR module /src/components/media/SanityMuxVideo.client.tsx:
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/runner/work/penny-morrison/penny-morrison/node_modules/@mux/mux-video-react/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/runner/work/penny-morrison/penny-morrison/node_modules/@mux/mux-video-react/dist/index.cjs.js:1:601
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at async nodeImport (/home/runner/work/penny-morrison/penny-morrison/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:50387:21)
    at async eval (/src/components/media/SanityMuxVideo.client.tsx?no-proxy:6:31)
    at async instantiateModule (/home/runner/work/penny-morrison/penny-morrison/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:50317:9)
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Building client code ...
9:14:11 PM [vite] Error when evaluating SSR module /src/components/portableText/blocks/Video.server.tsx:
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/runner/work/penny-morrison/penny-morrison/node_modules/@mux/mux-video-react/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/runner/work/penny-morrison/penny-morrison/node_modules/@mux/mux-video-react/dist/index.cjs.js:1:601
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at async nodeImport (/home/runner/work/penny-morrison/penny-morrison/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:50387:21)
    at async eval (/src/components/media/SanityMuxVideo.client.tsx?no-proxy:6:31)
    at async instantiateModule (/home/runner/work/penny-morrison/penny-morrison/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:50317:9)
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Building client code ...
9:14:11 PM [vite] Error when evaluating SSR module /src/components/portableText/PortableText.server.tsx:
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/runner/work/penny-morrison/penny-morrison/node_modules/@mux/mux-video-react/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/runner/work/penny-morrison/penny-morrison/node_modules/@mux/mux-video-react/dist/index.cjs.js:1:601
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at async nodeImport (/home/runner/work/penny-morrison/penny-morrison/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:50387:21)
    at async eval (/src/components/media/SanityMuxVideo.client.tsx?no-proxy:6:31)
    at async instantiateModule (/home/runner/work/penny-morrison/penny-morrison/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:50317:9)
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Building client code ...
9:14:11 PM [vite] Error when evaluating SSR module /src/components/modules/ContactForm.server.tsx:
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/runner/work/penny-morrison/penny-morrison/node_modules/@mux/mux-video-react/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/runner/work/penny-morrison/penny-morrison/node_modules/@mux/mux-video-react/dist/index.cjs.js:1:601
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at async nodeImport (/home/runner/work/penny-morrison/penny-morrison/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:50387:21)
    at async eval (/src/components/media/SanityMuxVideo.client.tsx?no-proxy:6:31)
    at async instantiateModule (/home/runner/work/penny-morrison/penny-morrison/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:50317:9)
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Building client code ...
9:14:11 PM [vite] Error when evaluating SSR module /src/components/modules/Module.server.tsx:
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/runner/work/penny-morrison/penny-morrison/node_modules/@mux/mux-video-react/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/runner/work/penny-morrison/penny-morrison/node_modules/@mux/mux-video-react/dist/index.cjs.js:1:601
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at async nodeImport (/home/runner/work/penny-morrison/penny-morrison/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:50387:21)
    at async eval (/src/components/media/SanityMuxVideo.client.tsx?no-proxy:6:31)
    at async instantiateModule (/home/runner/work/penny-morrison/penny-morrison/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:50317:9)
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Building client code ...
9:14:11 PM [vite] Error when evaluating SSR module /src/components/modules/ModuleGrid.server.tsx:
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/runner/work/penny-morrison/penny-morrison/node_modules/@mux/mux-video-react/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/runner/work/penny-morrison/penny-morrison/node_modules/@mux/mux-video-react/dist/index.cjs.js:1:601
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at async nodeImport (/home/runner/work/penny-morrison/penny-morrison/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:50387:21)
    at async eval (/src/components/media/SanityMuxVideo.client.tsx?no-proxy:6:31)
    at async instantiateModule (/home/runner/work/penny-morrison/penny-morrison/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:50317:9)
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Building client code ...
9:14:11 PM [vite] Error when evaluating SSR module /src/routes/[handle].server.tsx:
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/runner/work/penny-morrison/penny-morrison/node_modules/@mux/mux-video-react/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/runner/work/penny-morrison/penny-morrison/node_modules/@mux/mux-video-react/dist/index.cjs.js:1:601
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at async nodeImport (/home/runner/work/penny-morrison/penny-morrison/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:50387:21)
    at async eval (/src/components/media/SanityMuxVideo.client.tsx?no-proxy:6:31)
    at async instantiateModule (/home/runner/work/penny-morrison/penny-morrison/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:50317:9)
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Building client code ...
9:14:11 PM [vite] Error when evaluating SSR module virtual__hydrogen-routes.server.jsx:
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/runner/work/penny-morrison/penny-morrison/node_modules/@mux/mux-video-react/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/runner/work/penny-morrison/penny-morrison/node_modules/@mux/mux-video-react/dist/index.cjs.js:1:601
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at async nodeImport (/home/runner/work/penny-morrison/penny-morrison/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:50387:21)
    at async eval (/src/components/media/SanityMuxVideo.client.tsx?no-proxy:6:31)
    at async instantiateModule (/home/runner/work/penny-morrison/penny-morrison/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:50317:9)
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Building client code ...
9:14:11 PM [vite] Error when evaluating SSR module virtual__proxy__hydrogen-routes.server.jsx:
ReferenceError: module is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/home/runner/work/penny-morrison/penny-morrison/node_modules/@mux/mux-video-react/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/runner/work/penny-morrison/penny-morrison/node_modules/@mux/mux-video-react/dist/index.cjs.js:1:601
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at async nodeImport (/home/runner/work/penny-morrison/penny-morrison/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:50387:21)
    at async eval (/src/components/media/SanityMuxVideo.client.tsx?no-proxy:6:31)
    at async instantiateModule (/home/runner/work/penny-morrison/penny-morrison/node_modules/vite/dist/node/chunks/dep-6e2fe41e.js:50317:9)
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
Building client code ...

╭─ error ──────────────────────────────────────────────────────────────────────╮
│                                                                              │
│  Could not load server build entries: module is not defined in ES module     │
│  scope                                                                       │
│  This file is being treated as an ES module because it has a '.js' file      │
│  extension and '/home/runner/work/penny-morrison/penny-morrison/node_module  │
│  s/@mux/mux-video-react/package.json' contains "type": "module". To treat    │
│  it as a CommonJS script, rename it to use the '.cjs' file extension.        │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
❌ Cancelling deployment...
✅ Done in 0.32s.

🛑 exit status 1
```

### What version of the package are you using?

0.7.14

**Comment by cjpillsbury** [comment]
Hey @Mithrandiirr we're looking into this now! Thanks for the report

**Comment by cjpillsbury** [comment]
@Mithrandiirr without having full context on your setup, I won't know for sure, but our most recent release of mux-video-react (`@mux/mux-video-react@0.7.17`) may resolve your issue. Whenever you get a chance, give that new version a try and if it fixes your issue please let us know!

**Comment by Mithrandiirr** [comment]
Thanks for the reply, I found the issue is related to another library, had to update it.
